"""Domain Models for AutoPatch-CI."""

from datetime import datetime, timezone
from enum import Enum
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class PipelineStage(str, Enum):
    INGESTED = "INGESTED"
    LOGS_PARSED = "LOGS_PARSED"
    PATCH_GENERATED = "PATCH_GENERATED"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    PR_CREATED = "PR_CREATED"
    FAILED = "FAILED"


class CIFailureEvent(BaseModel):
    """Event representing a CI/CD build failure webhook trigger."""
    repo: str = Field(..., description="GitHub repository full name, e.g. 'owner/repo'")
    commit_sha: str = Field(..., description="Commit SHA that triggered the failed run")
    branch: str = Field(..., description="Branch name where failure occurred")
    run_id: str = Field(..., description="Workflow run ID")
    workflow_name: str = Field(default="CI", description="Name of the failing workflow")
    action_source: str = Field(default="github_app", description="Trigger source: 'github_app' or 'github_action'")
    installation_id: Optional[int] = Field(default=None, description="GitHub App installation ID if applicable")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class LogAnalysisResult(BaseModel):
    """Result of analyzing raw CI build logs using LLM parser."""
    run_id: str
    error_summary: str
    error_type: str  # e.g., 'SyntaxError', 'NullPointer', 'AssertionError', 'TypeScriptError'
    target_file_path: Optional[str] = None
    target_line_number: Optional[int] = None
    raw_stack_trace: str
    code_context: Optional[str] = None


class CodeFilePatch(BaseModel):
    """Individual file modification generated by the agent."""
    file_path: str
    original_content: Optional[str] = None
    patched_content: str
    is_new_file: bool = False


class GeneratedPatch(BaseModel):
    """Complete patch containing code fixes and regression test cases."""
    fix_files: List[CodeFilePatch]
    regression_test_file: CodeFilePatch
    rationale: str
    attempt_number: int = 1


class VerificationResult(BaseModel):
    """Result of running verification in an isolated sandbox (Cloud Build / Local Docker)."""
    passed: bool
    attempt_number: int
    execution_output: str
    failed_test_count: int = 0
    error_logs: Optional[str] = None


class PullRequestInfo(BaseModel):
    """Metadata of the successfully created GitHub Pull Request."""
    pr_number: int
    html_url: str
    branch_name: str
    title: str
    body_markdown: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class DiagnosticTraceStep(BaseModel):
    """Observability trace step logged during agent pipeline execution."""
    step_id: str
    stage: PipelineStage
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    title: str
    detail: str
    payload: Optional[Dict[str, str]] = None
